### ISSUE TITLE
Which version of Pytorch Lightning are you using for this?

### ISSUE THREAD

**Issue by peeush-agarwal** [coderkol95/MLOps_stock_prediction#3]
Hello,
I think you haven't updated your requirements.txt and it is missing pytorch lightning version.

Thanks in advance

**Comment by misra-anupam** [comment]
Hi,

Model training is done on an Azure compute using environment file. The file is present in `config/training_env.yml`.

Pytorch version is 1.13.1. For other packages' version you may refer the config files
